version: '3'

services:
  web:
    image: samidarko/identity
    ports:
      - "8001:8000"
#    volumes:
#      - .:/app
    env_file: .env
    depends_on:
      - db

  db:
    ports:
      - 127.0.0.1:8082:5432
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - ./db-initialize.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  db-data:
